monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 165  # distance of participant from monitor (in cm)
  gamma: 0.454545454545  # specific value for gamma correction
  verbose: True

window:
  units: pix
  color: [0, 0, 0]
  size: [1920, 1080]

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV13

design:
  n_trials: 1
  start_duration: 0.4 ###################################################
  end_duration: 0.8
  fix_movie_interval: 1.0

various:
  piechart_width: 1 
  text_width: 14
  text_height: 22.5
  buttons: ['j', 'k', 'l', 'semicolon']
  button_size: 2  

stimuli:
  movie_files: []
  aperture_radius: 400
  fix_radius: 6
  fix_color: [1, 1, 1]
  fix_line_width: 0.25
  movie_size_pix: [1536,1080]

  